### ISSUE TITLE
Crash when trying to remove not added updatable

### ISSUE THREAD

**Issue by fzymek** [google/agera#114]
When trying to remove updateable which was not added app crashes with following stacktrace

`Caused by: java.lang.IllegalStateException: Updatable not added, cannot remove.
                                                                                at com.google.android.agera.BaseObservable.remove(BaseObservable.java:146)
                                                                                at com.google.android.agera.BaseObservable.removeUpdatable(BaseObservable.java:94)
                                                                                at com.google.android.agera.Repositories$SimpleRepository.removeUpdatable(Repositories.java:94)
                                                                                at pl.fzymek.weatherprojector.viewmodel.SelectCityViewModel.shutdown(SelectCityViewModel.java:88)
                                                                                at pl.fzymek.weatherprojector.presentation.select.SelectCityActivity.onDestroy(SelectCityActivity.java:35)`

Maybe it should just do nothing like `ArrayList#remove(Object)`

**Comment by ernstsson** [comment]
It's intentional, unpaired add/remove leads to bugs that are seriously hard to track down (memory leaks, unintentionally increased network traffic etc.), this helps to prevent incorrect usage.

The documentation is clear on this too:

`throws IllegalStateException if the Updatable was not added`
