### ISSUE TITLE
demo crash on huawei honor 6.0

### ISSUE THREAD

**Issue by darin-lao** [google/agera#35]
[ 04-25 10:02:40.358  3009: 3009 E/         ]
process stopped due to unexpected signal 13
04-25 10:02:40.358 18767-18767/com.google.android.agera.testapp D/HwCust: Create obj success use class android.widget.HwCustTextViewImpl
04-25 10:02:40.372 18767-18767/com.google.android.agera.testapp I/HwCust: Constructor found for class android.widget.HwCustTextViewImpl
04-25 10:02:40.372 18767-18767/com.google.android.agera.testapp D/HwCust: Create obj success use class android.widget.HwCustTextViewImpl
04-25 10:02:40.400 18767-18793/com.google.android.agera.testapp I/System: core_booster, getBoosterConfig = true
04-25 10:02:40.435 18767-18767/com.google.android.agera.testapp D/StrictMode: StrictMode policy violation; ~duration=7 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=327711 violation=2
                                                                                  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1275)
                                                                                  at libcore.io.BlockGuardOs.access(BlockGuardOs.java:67)
                                                                                  at java.io.File.doAccess(File.java:284)
                                                                                  at java.io.File.exists(File.java:364)
                                                                                  at huawei.android.hwutil.ZipFileCache.openZipFile(ZipFileCache.java:145)
                                                                                  at huawei.android.hwutil.ZipFileCache.<init>(ZipFileCache.java:73)
                                                                                  at huawei.android.hwutil.ZipFileCache.getAndCheckCachedZipFile(ZipFileCache.java:81)
                                                                                  at android.content.res.HwResources.getThemeDrawable(HwResources.java:710)
                                                                                  at android.content.res.HwResources.loadDrawable(HwResources.java:652)
                                                                                  at android.content.res.TypedArray.getDrawable(TypedArray.java:912)
                                                                                  at android.view.View.<init>(View.java:3999)
                                                                                  at android.widget.ImageView.<init>(ImageView.java:145)
                                                                                  at android.widget.ImageButton.<init>(ImageButton.java:84)
                                                                                  at android.widget.ImageButton.<init>(ImageButton.java:80)
                                                                                  at android.widget.ActionMenuPresenter$OverflowMenuButton.<init>(ActionMenuPresenter.java:862)
                                                                                  at android.widget.ActionMenuPresenter.initForMenu(ActionMenuPresenter.java:170)
                                                                                  at com.android.internal.view.menu.MenuBuilder.addMenuPresenter(MenuBuilder.java:229)
                                                                                  at android.widget.Toolbar.setMenu(Toolbar.java:404)
                                                                                  at com.android.internal.widget.ToolbarWidgetWrapper.setMenu(ToolbarWidgetWrapper.java:391)
                                                                                  at com.android.internal.widget.ActionBarOverlayLayout.setMenu(ActionBarOverlayLayout.java:795)
                                                                                  at com.android.internal.policy.PhoneWindow.preparePanel(PhoneWindow.java:586)
                                                                                  at com.android.internal.policy.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:970)
                                                                                  at com.android.internal.policy.PhoneWindow$1.run(PhoneWindow.java:285)
                                                                                  at android.os.Handler.handleCallback(Handler.java:743)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:150)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
04-25 10:02:40.436 18767-18767/com.google.android.agera.testapp D/AndroidRuntime: Shutting down VM
04-25 10:02:40.436 18767-18767/com.google.android.agera.testapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.google.android.agera.testapp, PID: 18767
                                                                                  android.os.StrictMode$StrictModeViolation: policy=327711 violation=2
                                                                                      at android.os.StrictMode.executeDeathPenalty(StrictMode.java:1522)
                                                                                      at android.os.StrictMode.access$1300(StrictMode.java:122)
                                                                                      at android.os.StrictMode$AndroidBlockGuardPolicy.handleViolation(StrictMode.java:1515)
                                                                                      at android.os.StrictMode$AndroidBlockGuardPolicy$1.run(StrictMode.java:1397)
                                                                                      at android.os.Handler.handleCallback(Handler.java:743)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:150)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
04-25 10:02:40.749 18767-18767/com.google.android.agera.testapp I/Process: Sending signal. PID: 18767 SIG: 9

**Comment by ernstsson** [comment]
Looks like huawei.android.hwutil in the platform itself is doing strict mode violations. Line 83/84 of NotesActivity are setting strict mode to penaltyDeath(). I'd prefer to keep these lines in the test app just to keep track of strict violations.
Would you be cool with simply removing these lines when running the test app on your Huawei device? Strictly speaking I wouldn't have these set in a prod app like this, but for a test app I find it pretty helpful.
I might consider making the check a bit more lax, removing penaltyDeath(). Let me know how it goes.

**Comment by wang-qian** [comment]
My phone is huawei mate 6.0 OS,meet the same problem. I removing penaltyDeath()  solve the problem, thanks @ernstsson

**Comment by darin-lao** [comment]
removing penaltyDeath() is work !!

**Comment by zdRan** [comment]
But in my code is not used penaltyDeath (), how can I do?

this my log:

`05-10 22:39:45.340 21342-21359/com.xxx.umarket E/HAL: load: id=gralloc != hmi->id=gralloc
05-10 22:39:45.370 21342-21342/com.xxx.umarket W/System: ClassLoader referenced unknown path: /data/app/com.xxx.umarket-1/lib/arm
                                                         
                                                         [ 05-10 22:39:45.388  3739: 3739 E/         ]
                                                         process stopped due to unexpected signal 13
`

**Comment by TomakaZub** [comment]
zdRan did you find a solution ? I've the same error message. 

My application doesn't want to get started. Installation is ok, but i've a crash. 

My log : 
```
06-17 00:33:16.320 30737-30737/? I/art: Late-enabling -Xcheck:jni
06-17 00:33:16.363 30737-30751/fr.eni.ecole.android.ojm16.androcado E/HAL: load: id=gralloc != hmi->id=gralloc
06-17 00:33:16.429 30737-30737/fr.eni.ecole.android.ojm16.androcado W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/fr.eni.ecole.android.ojm16.androcado-1/split_lib_dependencies_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@fr.eni.ecole.android.ojm16.androcado-1@split_lib_dependencies_apk.apk@classes.dex) because non-0 exit status
                                                                           
                                                                           [ 06-17 00:33:16.471  2904: 2904 E/         ]
                                                                           process stopped due to unexpected signal 13
06-17 00:33:16.557 30737-30737/fr.eni.ecole.android.ojm16.androcado W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --dex-file=/data/app/fr.eni.ecole.android.ojm16.androcado-1/split_lib_slice_1_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@fr.eni.ecole.android.ojm16.androcado-1@split_lib_slice_1_apk.apk@classes.dex) because non-0 exit status
06-17 00:33:16.563 30737-30737/fr.eni.ecole.android.ojm16.androcado W/System: ClassLoader referenced unknown path: /data/app/fr.eni.ecole.android.ojm16.androcado-1/lib/arm64
06-17 00:33:16.569 30737-30737/fr.eni.ecole.android.ojm16.androcado I/InstantRun: starting instant run server: is main process
06-17 00:33:16.616 30737-30737/fr.eni.ecole.android.ojm16.androcado I/HwCust: Constructor found for class android.app.HwCustHwWallpaperManagerImpl
06-17 00:33:16.950 30737-30737/fr.eni.ecole.android.ojm16.androcado I/Process: Sending signal. PID: 30737 SIG: 9
```

**Comment by smile616** [comment]
zdRan/TomakaZub,

could you try disable the Instant run in the Android studio?

**Comment by TomakaZub** [comment]
I tried it, but same problem...
